C
C       DEMONSTRATION TEST PROGRAM FOR RT11 FORTRAN IV V2
C
        TYPE 100
100     FORMAT(' ***** RT11 FORTRAN IV V2 DEMONSTRATION TEST *****')
        A = 3.14159
        A = A / 3.14159
        IF (A.NE.1.0) TYPE 200
200     FORMAT('0ERROR IN FLOATING POINT ARITHMETIC TEST.')
        I = A
        I = I*8 / 4
        IF (I.NE.2) TYPE 300
300     FORMAT('0ERROR IN INTEGER ARITHMETIC TEST.')
        TYPE 400
400     FORMAT('0INSTALLATION SUCCESSFUL IF NO ERROR MESSAGES',/
        +       '              WERE PRINTED ABOVE.')
        TYPE 500
500     FORMAT('0**** FORTRAN DEMONSTRATION TEST COMPLETE *****')
        CALL EXIT
        END

