PROGRAM ch2610
IMPLICIT NONE

INTERFACE
  ELEMENTAL SUBROUTINE SWAP(X,Y)
  INTEGER , INTENT(INOUT) :: X,Y
  END SUBROUTINE SWAP
END INTERFACE

INTEGER , DIMENSION(10) :: A,B
INTEGER :: I
  DO I=1,10
    A(I)=I
    B(I)=I*I
  END DO
    PRINT *,A
    PRINT *,B
    CALL SWAP(A,B)
    PRINT *,A
    PRINT *,B
END PROGRAM ch2610

ELEMENTAL SUBROUTINE SWAP(X,Y)
INTEGER , INTENT(INOUT) :: X,Y
INTEGER :: TEMP
  TEMP=X
  X=Y
  Y=TEMP
END SUBROUTINE SWAP