PROGRAM ch2609
IMPLICIT NONE
!
! Elemental function example
!
INTEGER :: I
REAL :: X
REAL , DIMENSION(10) :: Y

INTERFACE
  ELEMENTAL REAL FUNCTION ETOX(X)
  IMPLICIT NONE
  REAL , INTENT(IN) :: X
  END FUNCTION ETOX
END INTERFACE

  X=1.0
  DO I=1,10
    Y(I)=I
  END DO
  PRINT *,Y
  X=ETOX(X)
  PRINT *,X
  Y=ETOX(Y)
  PRINT *,Y
END PROGRAM ch2609

ELEMENTAL REAL FUNCTION ETOX(X)
IMPLICIT NONE
REAL , INTENT(IN) :: X
REAL :: TERM
INTEGER :: NTERM
REAL , PARAMETER :: TOL =1.0E-6
  ETOX=1.0
  TERM=1.0
  NTERM=0
  DO
    NTERM=NTERM+1
    TERM=(X/NTERM)*TERM
    ETOX=ETOX+TERM
    IF (TERM<=TOL) EXIT
  END DO
END FUNCTION ETOX