      SUBROUTINE FR1(N,M,CSTR)
      INTEGER*4 CSTR(1)
C     HERE WE RECEIVE THE C CHAR STRING IN AN INTEGER ARRAY
C     COULD ALSO HAVE USED A BYTE ARRAY
      M=N*N
      WRITE(6,20) (CSTR(L),L=1,3)
   20 FORMAT(' CSTR=',3A4)
      WRITE(6,*) 'DONE'
      RETURN
      END
